name: Build Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: |
          echo "${{ secrets.KEYSTORE_GPG }}" > release.keystore.asc
          gpg --batch --passphrase "${{ secrets.GPG_PASSWORD }}" -d -o release.keystore release.keystore.asc
          echo "${{ secrets.CHAIN_GPG }}" > chain.p7b.asc
          gpg --batch --passphrase "${{ secrets.GPG_PASSWORD }}" -d -o chain.p7b release.keystore.asc
          echo keystoreFile=release.keystore > signing.properties
          echo keystorePassword="${{ secrets.KEYSTORE_PASSWORD }}" > signing.properties
          echo certFile=chain.p7b > signing.properties
          echo certPassword="${{ secrets.CERT_PASSWORD }}" > signing.properties
          echo certAlias=ignition > signing.properties
          ./gradlew build -PpropertyFile=signing.properties --stacktrace --debug
